Fix webservices app connector
CompassionCH/compassion-modules pull request #1003
Opened 2019-04-08 12:21 UTC by jonathantarabbia

- Fix get tiles when Offline
 - Fix get tiles when logged
 - Fix get Children when tile.mode is many
 - Fix Mapping of child object
 - Add Child pictures Object and Mapping
 - Fix Tile CH2 webservices

2019-04-09 12:37 UTC, ecino requested changes
You should rebase onto compassion/devel and remove your commit AP-47, because it's already merged.

2019-04-09 12:37 UTC, ecino commented on mobile_app_connector/controllers/mobile_app_controller.py
> +            # ('type', 'ilike', hero_type),
Is the app not providing the hero_type ? Why did you remove this ? It means we won't be able to display different banners depending if the user is logged in or not.

2019-04-09 12:37 UTC, ecino commented on mobile_app_connector/models/app_hub.py
> +                               children_pictures=None, start=0, limit=100,
You added this parameter, but it's never used in the method?

2019-04-09 13:59 UTC, jonathantarabbia commented on mobile_app_connector/models/app_hub.py
> +                               children_pictures=None, start=0, limit=100,
indeed, it is not necessary

2019-04-10 12:48 UTC, ecino commented on mobile_app_connector/controllers/mobile_app_controller.py
> +            # ('type', 'ilike', hero_type),
I checked and iOS neither gives this parameter. Therefore I propose that you remove the parameter `hero_type` from the function and that you remove as well the field `type` in the object `mobile.app.banner`, as it won't be useful if it's not supported by the app. We can therefore only define one banner that is active for both public and private.

2019-04-10 14:39 UTC, ecino requested changes

2019-04-10 14:39 UTC, ecino commented on mobile_app_connector/models/compassion_child.py
> +                               .get_app_json(multi=True)]}
```suggestion
                           .get_app_json(multi=True)]}
```

2019-04-10 14:39 UTC, ecino commented on mobile_app_connector/mappings/compassion_child_pictures_mapping.py
> +
```suggestion

```
(make sure you have just a line return without any space or content on the last line)
https://github.com/PyCQA/pycodestyle/issues/365

2019-04-11 08:00 UTC, merged