CO-2555 Remplacer le calcul du champ invoice_type
CompassionCH/compassion-modules pull request #1035
Opened 2019-05-01 09:52 UTC by quentingigon

I couldn't yet test the code because of a bug preventing me from accessing invoice_lines in odoo

2019-05-01 14:08 UTC, ecino requested changes

2019-05-01 14:08 UTC, ecino commented on sponsorship_compassion/models/account_invoice.py
> -
Don't remove the blank line

2019-05-01 14:08 UTC, ecino commented on sponsorship_compassion/models/account_invoice.py
> +            sponsorship_cat = self.env.ref('product.product_category_3')
`product_category_3` is in a demo file and is equivalent to the `Services` category. It is not at all the Sponsorship category.

2019-05-01 14:08 UTC, ecino commented on sponsorship_compassion/models/account_invoice.py
> +            category = self.env['product.category'].search([
No it should be like :
```
            category_lines = self.env['account.invoice.line'].search([
                ('invoice_id', '=', invoice.id),
                ('product_id.categ_id', 'child_of', sponsorship_cat.id)
```
Please change the others as well.

2019-05-01 14:08 UTC, ecino commented on sponsorship_compassion/models/account_invoice.py
> +            fund_cat = self.env.ref('product.product_category_4')
No

2019-05-01 14:08 UTC, ecino commented on sponsorship_compassion/models/account_invoice.py
> +            gift_cat = self.env.ref('product.product_category_5')
No

2019-05-01 14:09 UTC, ecino commented
> I couldn't yet test the code because of a bug preventing me from accessing invoice_lines in odoo

Then you should come and ask me. We will look this next time you are here.

2019-05-08 07:35 UTC, quentingigon commented
I applied your change requests and tested that the value is correctly computed when state of account.invoice changes

2019-05-08 12:19 UTC, ecino requested changes

2019-05-08 12:19 UTC, ecino commented on sponsorship_compassion/models/account_invoice.py
> +                'sponsorship_compassion.product_template_fund_gen')
```suggestion
                'contract_compassion.product_category_fund', -1)
```

2019-05-08 12:19 UTC, ecino commented on sponsorship_compassion/models/account_invoice.py
> +                'sponsorship_compassion.product_category_sponsorship')
To avoid error at module init, we use a default value if the xml reference is not yet loaded.
```suggestion
                'sponsorship_compassion.product_category_sponsorship', -1)
```

2019-05-08 12:19 UTC, ecino commented on sponsorship_compassion/models/account_invoice.py
> +                'sponsorship_compassion.product_category_gift')
```suggestion
                'sponsorship_compassion.product_category_gift', -1)
```

2019-05-21 07:28 UTC, closed without merging