salutation full name
CompassionCH/compassion-modules pull request #1050
Opened 2019-05-21 12:18 UTC by joblo-compassion

2019-05-21 12:19 UTC, joblo-compassion commented
https://github.com/CompassionCH/compassion-switzerland/pull/883
linked pull request

2019-05-23 09:14 UTC, ecino requested changes

2019-05-23 09:14 UTC, ecino commented on thankyou_letters/models/res_partner.py
> +                partner.informal_salutation = partner.salutation
Why did you change the `informal_salutation`? It's not good, it looks like the same, but the informal is in singular `friend` vs `friends`. Please revert this change. The `full_salutation` should be equal to the normal salutation (this is right).

2019-05-28 13:37 UTC, joblo-compassion commented
======== Testing test_flake8 ========
sbc_compassion/models/contracts.py:90:17: F841 local variable 'write_for_birthday_alert' is assigned to but never used

The problem is that is localy true

2019-06-04 06:54 UTC, ecino approved these changes

2019-06-04 06:54 UTC, merged