AP-75 Implement contact us
CompassionCH/compassion-modules pull request #1094
Opened 2019-07-02 07:35 UTC by vwvw

2019-07-05 09:41 UTC, ecino requested changes

2019-07-05 09:41 UTC, ecino commented on mobile_app_connector/security/ir.model.access.csv
> +create_access_mobile_app_public_contact_us,User not logged can create crm claim,model_crm_claim,base.group_public,1,1,1,0
If you use sudo() inside the method `mobile_contact_us`, I think it's not needed to add that access rule which would open maybe too much rights

2019-07-05 09:42 UTC, ecino commented on mobile_app_connector/models/request.py
> +            'code': self.env.ref('crm_claim_code.sequence_claim_app').sudo()._next(),
Please fix your lines too long.

2019-07-05 13:13 UTC, ecino commented
Two flak8 issues:
```
mobile_app_connector/models/request.py:52:70: E502 the backslash is redundant between brackets
mobile_app_connector/models/request.py:53:17: E131 continuation line unaligned for hanging indent
```

2019-07-05 13:36 UTC, vwvw commented
Should be good now

2019-07-08 07:45 UTC, ecino commented on mobile_app_connector/models/request.py
> +        message = claim.message_post()
Why not directly giving the body and subject in the method ? I think the method handles that.
```
        message = claim.message_post(body='...', subject='...')
```

2019-07-08 07:59 UTC, ecino approved these changes

2019-07-08 08:00 UTC, merged