AP-253 Not logged in users can access FAQ
CompassionCH/compassion-modules pull request #1144
Opened 2019-08-27 11:13 UTC by about-blank4

2019-08-28 09:10 UTC, ecino requested changes

2019-08-28 09:10 UTC, ecino commented on mobile_app_connector/controllers/mobile_app_controller.py
> +                 '/mobile-app-api/frequently.asked.questions/get_faq/'],
Why having twice the same path?

2019-08-28 09:10 UTC, ecino commented on mobile_app_connector/controllers/mobile_app_controller.py
> +        odoo_obj = request.env.get('frequently.asked.questions').with_context(
No need to convert language
```suggestion
        faq_handler = request.env.get('frequently.asked.questions')
```

2019-08-28 09:10 UTC, ecino commented on mobile_app_connector/controllers/mobile_app_controller.py
> +        model_method = 'mobile_get_faq'
Here you can directly call the method, no need to search for it, as it's not meant to be generic...
```suggestion
        return faq_handler.mobile_get_faq(**parameters)
```

2019-08-28 14:13 UTC, ecino commented
Please check privacy statement route as well, I think the same problem happens for it.

2019-08-28 14:50 UTC, about-blank4 commented
Corrected route for privacy statement as well (yes there was the same bug for this route)

2019-08-29 07:21 UTC, ecino approved these changes
Thank you!

2019-08-29 07:22 UTC, merged