CO-2708: updating the traduction file with poeditor. there is still s…
CompassionCH/compassion-modules pull request #1146
Opened 2019-08-28 15:07 UTC by samybucher

…ome files missing in the french dossier, german didnt come in the commit, I'll check this tomorrow

2019-08-28 15:10 UTC, samybucher commented
with german file this time!

2019-08-29 06:39 UTC, ecino requested changes
Thanks! Some letters are missing.

2019-08-29 06:39 UTC, ecino commented on child_compassion/i18n/de.po
> +"ie Kinder können jedes Jahr ausserhalb des Lehrplans ein Lager besuchen. Sie "
```suggestion
"Die Kinder können jedes Jahr ausserhalb des Lehrplans ein Lager besuchen. Sie "
```

2019-08-29 06:39 UTC, ecino commented on child_compassion/i18n/de.po
> +"ie Kinder in Togo erhalten jeden Tag, an dem sie ins Zentrum kommen, ein "
```suggestion
"Die Kinder in Togo erhalten jeden Tag, an dem sie ins Zentrum kommen, ein "
```

2019-08-29 06:39 UTC, ecino commented on child_compassion/i18n/de.po
> +"eden Monat wird eine Campingzeit angeboten, an der die Kinder teilnehmen "
```suggestion
"Eden Monat wird eine Campingzeit angeboten, an der die Kinder teilnehmen "
```
Beginning of sentence, should it be a capital letter?

2019-08-29 06:39 UTC, ecino commented on child_compassion/i18n/de.po
> +"ie Kinder und Jugendlichen haben Spass, knüpfen Freundschaften und können in "
```suggestion
"Die Kinder und Jugendlichen haben Spass, knüpfen Freundschaften und können in "
```

2019-08-29 06:39 UTC, ecino commented on child_compassion/i18n/de.po
> +"ie Kinder und Jugendlichen haben Spass, knüpfen Freundschaften und können in "
```suggestion
"Die Kinder und Jugendlichen haben Spass, knüpfen Freundschaften und können in "
```

2019-08-29 06:39 UTC, ecino commented on child_compassion/i18n/de.po
> +"ie Mitarbeitenden des Kinderzentrums vermitteln wertvolle Lebensweisheiten, "
```suggestion
"Die Mitarbeitenden des Kinderzentrums vermitteln wertvolle Lebensweisheiten, "
```

2019-08-29 07:58 UTC, ecino commented
Thank you. I'm waiting for the missing translations and we will merge afterwards. You forgot as well to fix the missing letters in German, can you look at it?

2019-08-30 08:37 UTC, ecino commented
Missing translation for Honduras:
```
Les repas servis aux enfants sont en principe constitués de viande, de légumes, de céréales, de fruits et de jus de fruits. Les enfants souffrant de malnutrition bénéficient de compléments alimentaires, selon les indications données par le personnel médical.
```

2019-08-30 08:38 UTC, ecino commented
For the other translation, Christian told me the text is not useful. So you can just put a space as the translation so that it won't display anything.

2019-08-30 08:57 UTC, ecino approved these changes
:+1:

2019-08-30 08:58 UTC, merged