CO-2848 sms_sponsorship migration v11
CompassionCH/compassion-modules pull request #1226
Opened 2019-12-06 08:58 UTC by josueBulle

depends on another pull request

crm_compassion -> crm_request -> crm_claim_type)

2020-01-10 12:47 UTC, ecino commented
flake8 issues (alignment) :
``` 
sms_sponsorship/models/sms_child_request.py:241:17: E122 continuation line missing indentation or outdented
sms_sponsorship/models/sms_child_request.py:242:17: E122 continuation line missing indentation or outdented
sms_sponsorship/models/sms_child_request.py:243:17: E122 continuation line missing indentation or outdented
sms_sponsorship/models/sms_child_request.py:244:17: E122 continuation line missing indentation or outdented
sms_sponsorship/models/sms_child_request.py:245:17: E122 continuation line missing indentation or outdented
sms_sponsorship/models/sms_child_request.py:246:17: E122 continuation line missing indentation or outdented
sms_sponsorship/models/sms_child_request.py:247:17: E122 continuation line missing indentation or outdented
sms_sponsorship/models/sms_child_request.py:248:17: E122 continuation line missing indentation or outdented
sms_sponsorship/models/sms_child_request.py:249:17: E122 continuation line missing indentation or outdented
sms_sponsorship/models/sms_child_request.py:250:13: E122 continuation line missing indentation or outdented
```

2020-01-21 09:54 UTC, ecino requested changes

2020-01-21 09:54 UTC, ecino commented on sms_sponsorship/models/sms_child_request.py
> +    sender = fields.Char('Phone')
The model should inherit from `phone.validation.mixin` and add a property `_phone_name_fields = ['sender']`

2020-01-23 15:32 UTC, ecino requested changes
You have places in the code where you still access `staff.notification.settings`. Please replace it by `res.config.settings` to avoid errors. I don't know if it's as well related to your changes, but the Compassion settings view is broken:
![image](https://user-images.githubusercontent.com/8435180/72998312-ed91d880-3dfd-11ea-9945-46329343cfb1.png)

2020-01-23 16:11 UTC, josueBulle commented
> I don't know if it's as well related to your changes, but the Compassion settings view is broken:

This field is defined in the OCA module "base_phone" and isn't related to this PR
(Note that it is present in all the sections, even with sms_sponsorship uninstalled)

2020-01-24 12:42 UTC, ecino approved these changes

2020-01-24 12:42 UTC, merged