Hr attendance management migration v11
CompassionCH/compassion-modules pull request #1237
Opened 2019-12-17 09:57 UTC by quentingigon

2020-01-21 09:55 UTC, ecino commented
hr_attendance_management/models/hr_employee.py:86:89: E501 line too long (92 > 88 characters)
@eicher31 please review

2020-01-28 12:41 UTC, eicher31 requested changes
FAIL: test_period_balances (odoo.addons.hr_attendance_management.tests.test_periods.TestPeriod)                                                   
Traceback (most recent call last):                                                                                                                
`   File "/home/stephane/odoo/odoo11/review/compassion-modules/hr_attendance_management/tests/test_periods.py", line 224, in test_period_balances 
`     self.assertEquals(self.gilles.balance, 4)                                                                                                   
` AssertionError: 5.0 != 4

2020-01-28 12:41 UTC, eicher31 commented on hr_attendance_management/data/annual_balance_cron.xml
> +            <field name="function">_cron_compute_annual_balance</field>
Verify if it work:
2020-01-24 10:33:17,166 3357 WARNING v11c_hr_attendance odoo.models: ir.cron.create() includes unknown fields: function
Seem to be replace by the field "code":
https://webkul.com/blog/creating-cron-server-action-odoo-11/

2020-01-28 12:41 UTC, eicher31 commented on hr_attendance_management/data/attendance_computation_cron.xml
> +            <field name="function">_cron_create_attendance</field>
Same

2020-01-28 12:41 UTC, eicher31 commented on hr_attendance_management/views/hr_employee.xml
> +            <xpath expr="//div[@class='oe_kanban_details']/ul/li" position="after">
Use the hasclass(*classes) function to filter elements by their classes

2020-02-20 10:49 UTC, ecino commented
I think you should rebase onto branch 11.0 in order to fix the tests.

2020-02-21 10:14 UTC, eicher31 requested changes
Move the hr_attendance settings inside the general settings and update the view. Some fields have not label.

2020-02-21 10:14 UTC, eicher31 commented on hr_attendance_management/tests/test_periods.py
> +            'origin': "create"
WARNING v11c_hr_attendance_test odoo.models: hr.employee.period.create() includes unknown fields: origin

2020-02-21 10:14 UTC, eicher31 commented on hr_attendance_management/tests/test_periods.py
> +            'origin': "create"
WARNING v11c_hr_attendance_test odoo.models: hr.employee.period.create() includes unknown fields: origin

2020-02-21 10:14 UTC, eicher31 commented on hr_attendance_management/tests/test_periods.py
> +            'origin': "create"
same

2020-02-24 15:26 UTC, quentingigon commented
There is a problem with advanced_translation: it seems it can't launch the tests and after that the execution stops. Is it a problem with Travis ?

2020-02-25 09:59 UTC, quentingigon commented
I removed a dependency on partner-contact-gender as it was causing Travis to fail. This module did add the gender field to res.partner but the values were (male, Male) instead of (m, Male). I replaced the dependency by thankyou_letter, as it's this module that add the gender field

2020-02-25 10:42 UTC, eicher31 approved these changes

2020-02-25 10:42 UTC, merged