CO-3005 modification to controller.
CompassionCH/compassion-modules pull request #1287
Opened 2020-02-11 12:23 UTC by quentingigon

A second PR on compassion-switzerland implements second half of fix. When getting the sponsorship using browse, its parameters were then inaccessible

2020-02-20 10:28 UTC, ecino commented
Is it because sponsorship_id is a string? Then, could we just make browse(int(sponsorship_id)) instead? And maybe check that sponsorship_id is not None.

2020-02-20 10:28 UTC, ecino commented
https://github.com/CompassionCH/compassion-switzerland/pull/1004

2020-02-20 10:33 UTC, quentingigon commented
I will try it

2020-02-20 14:25 UTC, quentingigon commented
> Is it because sponsorship_id is a string? Then, could we just make browse(int(sponsorship_id)) instead?

No, I tried all possibilities and with browse(), I had no access to its parameters

2020-02-24 14:18 UTC, ecino requested changes

2020-02-24 14:18 UTC, ecino commented on sms_sponsorship/controllers/main.py
> +            raise Exception("Please provide a sponsorship_id")
raise NotFound() was better (for user interface), however you can add a line to log an error in the logs
```
import logging

_logger = logging.getLogger(__name__)

_logger.error("No sponsorship_id was given to the route")

2020-02-24 14:18 UTC, ecino commented on sms_sponsorship/controllers/main.py
> +                raise NotFound()
Add a log
```
_logger.error("No valid sponsorship found for given id : %s", sponsorship_id)
```

2020-02-25 10:02 UTC, ecino approved these changes

2020-02-25 10:02 UTC, merged