fixes
CompassionCH/compassion-modules pull request #1288
Opened 2020-02-11 15:31 UTC by josueBulle

- Fix logging feature port to v11
- file upload in cms_form
- Quentin v11 super() migration

2020-02-18 08:59 UTC, josueBulle commented
finally, I'm not sure it is a good idea to move the translations lines in csv (but they still need the fixes)

2020-02-19 15:07 UTC, ecino requested changes
The tests are broken.

2020-02-20 10:56 UTC, josueBulle commented
I think the tests fail on the branch v11 too, it might not be related to this pr

2020-02-20 14:23 UTC, ecino approved these changes

2020-02-20 14:23 UTC, merged