CO-3051 added activities to child/hold/request/correspondence/jobs
CompassionCH/compassion-modules pull request #1293
Opened 2020-02-18 13:27 UTC by josueBulle

related
https://github.com/CompassionCH/compassion-switzerland/pull/1016

2020-02-24 16:42 UTC, ecino requested changes

2020-02-24 16:42 UTC, ecino commented on child_compassion/models/child_compassion.py
>          'child.project.activity', string='Project activities', readonly=True)
please add property `oldname` for migration purpose: `oldname='activity_ids'`

2020-02-25 09:56 UTC, josueBulle commented
Should I have increased the manifest version?

2020-02-25 10:09 UTC, ecino commented
> Should I have increased the manifest version?

No it's fine.

2020-02-25 10:09 UTC, ecino approved these changes

2020-02-25 10:10 UTC, merged