CO-3097 La vue des Settings Compassion n'est pas bonne
CompassionCH/compassion-modules pull request #1297
Opened 2020-02-24 16:27 UTC by SylvainLosey

- For now all the subsettings that link to the Compassion settings page are still here, but it might be best to group them in a single Settings menu link, as is done in other modules such as Invoicing
- The OCA module connector-telephony/base_phone [adds its settings to all settings block](https://github.com/OCA/connector-telephony/blob/0eda4f60383b1bd7a3d0f4e97f8263996fcbd9b6/base_phone/views/res_config_settings.xml#L15) which is not ideal. I'm not sure how to handle this as this behavior changes in v12.

2020-02-25 15:08 UTC, ecino requested changes

2020-02-25 15:08 UTC, ecino commented on child_compassion/__manifest__.py
> +        'views/availability_management_view.xml',
You should put this after compassion_settings_view, because it depends on it and should therefore be loaded after.

2020-02-27 08:02 UTC, josueBulle reviewed
Visually it looks great but
As discussed, you need to migrate all the settings `set_values` and `get_value` methods (Now multiple fields are not writing new values on save).

(I used this regexp to find the use of old named settings that will raise an exception when executed:)
`env\[.((?!res.config).)*?.settings.\]`

2020-02-27 08:02 UTC, josueBulle commented on sponsorship_tracking/views/settings_view.xml
> +                                       for="sub_fr"/>
`sub_de` => `sub_fr`

2020-03-04 14:00 UTC, ecino approved these changes

2020-03-04 14:01 UTC, merged