Deactiate thankyou letters
CompassionCH/compassion-modules pull request #1342
Opened 2020-06-04 13:41 UTC by quentingigon

Added the field in the model and un-commented the filtering of invoices

2020-06-04 13:42 UTC, quentingigon commented
other half is [HERE](https://github.com/CompassionCH/compassion-switzerland/pull/1099)

2020-06-08 07:42 UTC, ecino requested changes
Please rename the field (and update all references in both pull requests).

2020-06-08 07:42 UTC, ecino commented on mobile_app_connector/models/account_invoice.py
> +    no_notifications = fields.Boolean(default=True)
Please rename the field to something more understandable.
```suggestion
    avoid_mobile_donation_notification = fields.Boolean(
        default=True, help='Uncheck to send a mobile notification for donation confirmation')
```

2020-06-08 08:10 UTC, ecino requested changes

2020-06-08 08:10 UTC, ecino commented on mobile_app_connector/views/account_invoice_view.xml
> +            <field name="returned_payment" position="after">
```suggestion
            <field name="date_due" position="after">
```

2020-06-08 08:52 UTC, ecino approved these changes

2020-06-08 08:52 UTC, merged