CO-3254 Implement resubmission of unsuccesful translation check
CompassionCH/compassion-modules pull request #1350
Opened 2020-06-23 13:13 UTC by SylvainLosey

I had a hard time testing this, not entirely sure about

```
# Concatenate the local_id and the current resubmit_id
if "local_id" in odoo_data:
    odoo_data["local_id"] = odoo_data["local_id"] + self.resubmit_id
```

as I didn't find a way to trigger a letter json_to_data from GMC

2020-07-07 12:58 UTC, ecino requested changes

2020-07-07 12:58 UTC, ecino commented on sbc_compassion/models/correspondence.py
> +
No, this is in the wrong method, you should do this in the method `data_to_json` to change the value we are sending to GMC.

2020-07-07 12:58 UTC, ecino commented on sbc_compassion/models/correspondence.py
> +            letter.resubmit_id += 1
```suggestion
            letter.resubmit_id += 1
            letter.create_commkit()
```

2020-07-07 12:58 UTC, ecino commented on sbc_compassion/views/correspondence_view.xml
> +        <field name="name">Resubmit letter translation</field>
```suggestion
        <field name="name">Resubmit letter to GMC</field>
```

2020-07-07 12:58 UTC, ecino commented on sbc_compassion/views/correspondence_view.xml
> +    <record id="resubmit_letter_translation_action" model="ir.actions.server">
```suggestion
    <record id="resubmit_letter_action" model="ir.actions.server">
```

2020-07-07 12:58 UTC, ecino commented on sbc_compassion/views/correspondence_view.xml
> +        <field name="name">Resubmit letter translation</field>
```suggestion
        <field name="name">Resubmit letter</field>
```

2020-07-07 12:58 UTC, ecino commented on sbc_compassion/views/correspondence_view.xml
> +        <field name="code">records.resubmit_letter_translation()</field>
```suggestion
        <field name="code">records.resubmit_letter()</field>
```

2020-07-07 12:58 UTC, ecino commented on sbc_compassion/views/correspondence_view.xml
> +                    <button name="resubmit_letter_translation" type="object"
```suggestion
                    <button name="resubmit_letter" type="object"
```

2020-07-07 12:58 UTC, ecino commented on sbc_compassion/views/correspondence_view.xml
> +                            string="Resubmit Letter Translation"
```suggestion
                            string="Resubmit Letter to GMC"
```

2020-07-07 12:58 UTC, ecino commented on sbc_compassion/views/correspondence_view.xml
> +    <record id="resubmit_letter_translation_action" model="ir.actions.server">
```suggestion
    <record id="resubmit_letter_action" model="ir.actions.server">
```

2020-07-07 12:58 UTC, ecino commented on sbc_compassion/models/correspondence.py
> +    def resubmit_letter_translation(self):
```suggestion
    def resubmit_letter(self):
```

2020-07-09 07:59 UTC, SylvainLosey commented
Requested changes applied

2020-07-23 07:39 UTC, ecino approved these changes

2020-07-23 07:41 UTC, merged