Co 3344 12.0 remove extra sponsorship
CompassionCH/compassion-modules pull request #1376
Opened 2020-07-07 10:03 UTC by wvmrtn

Removed extra icon "Sponsorship" in the main menu.

2020-07-07 12:40 UTC, ecino requested changes

2020-07-07 12:40 UTC, ecino commented on crm_compassion/views/sponsorship_view.xml
> -    </record>
This view was needed and should be restored. The others can be removed.

2020-07-08 11:45 UTC, wvmrtn commented
Restored previously deleted view.

2020-07-24 09:17 UTC, ecino approved these changes

2020-07-24 09:18 UTC, merged