CO-3195 / CO-3196 Add gift payment slips to support replies
CompassionCH/compassion-modules pull request #1420
Opened 2020-07-31 13:23 UTC by SylvainLosey

2020-08-05 09:29 UTC, Theyiot requested changes
Except for the typo in the comment, the rest looks fine to me.

2020-08-05 09:29 UTC, Theyiot commented on crm_request/models/mail_compose_message.py
> +        # Add reply qyote
Little typo in the comment.
```suggestion
        # Add reply quote
```

2020-08-06 12:28 UTC, ecino commented
@Theyiot Can you move these changes into crm_switzerland (as explained in JIRA issue that I reopened and assigned to you).

2020-08-06 12:28 UTC, closed without merging

2020-08-06 13:51 UTC, Theyiot commented
> @Theyiot Can you move these changes into crm_switzerland (as explained in JIRA issue that I reopened and assigned to you).

I'm working on it.