CO-3834: Changing correspondent of sponsorship doesn't work
CompassionCH/compassion-modules pull request #1590
Opened 2021-12-06 15:00 UTC by TheRaphael0000

- Refactor the workflow to handle each record one at the time
- Fix different issues in the current code

2021-12-06 15:02 UTC, TheRaphael0000 commented
The sponsorship cancellation seem to work
But I couldn't test the upsert since GMC return me errors that I don't understand (may be due to my development environment) : 

```
{
    "Beneficiary_GlobalID": "09201919",
    "Code": 5000,
    "Commitment_ID": null,
    "CorrespondentCommitmentID": null,
    "CorrespondentSupporterGlobalID": null,
    "HoldID": "",
    "Message": "Beneficiary Hold order not matched",
    "SponsorSupporterGlobalID": "06450834",
    "StartDate": null
}
```

2021-12-07 13:42 UTC, ecino requested changes

2021-12-07 13:42 UTC, ecino commented on sponsorship_compassion/models/contracts.py
> +        import json
Imports should all be at the beginning of the file.

2021-12-07 13:42 UTC, ecino commented on sponsorship_compassion/models/contracts.py
> +                    self.correspondent_id.update_number_sponsorships()
This should be moved inside the `_remove_correspondent` method, just before the commit.

2021-12-07 13:42 UTC, ecino commented on sponsorship_compassion/models/contracts.py
> +            self.message_post(body=message.failure_reason, subject=_("The sponsorship is no more active!"))
This is not useful because the raise just after will delete this message (by rolling back any changes).

2021-12-07 13:42 UTC, ecino commented on sponsorship_compassion/models/contracts.py
> +                record.correspondent_id.update_number_sponsorships()
You should move this inside `_add_correspondent` method, just before the commit.

2021-12-09 06:02 UTC, ecino requested changes

2021-12-09 06:02 UTC, ecino commented on sponsorship_compassion/models/contracts.py
> +        return super().write(vals)
Now you changed the order of execution by moving the super call at the end. It means that the changes in the sponsorship will only be processed after all our code which in my opinion is wrong for the other methods that were called after the super like `_on_language_changed` and `update_number_sponsorships` at line 542. Those two should still be after the super.

2021-12-09 07:28 UTC, ecino approved these changes

2021-12-09 07:29 UTC, merged