CS-491: Add new event logging function
CompassionCH/compassion-modules pull request #1596
Opened 2021-12-15 14:29 UTC by TheRaphael0000

- Add the Other Communication type to the "interaction resume"
- Add an "Log other" feature for res.partner (allow to specify the type, subject, body, direction)

2022-01-04 11:12 UTC, ecino requested changes

2022-01-04 11:12 UTC, ecino commented on crm_compassion/models/interaction_resume.py
> +    other_type = fields.Text()
To be consistent with the type used in the wizard.
```suggestion
    other_type = fields.Char()
```

2022-01-04 11:12 UTC, ecino commented on crm_compassion/views/partner_log_other_interaction_wizard_view.xml
> +                name="Log other"
```suggestion
                name="Log other interaction"
```

2022-01-04 12:37 UTC, TheRaphael0000 commented
I've commited you suggestion with the GitHub feature, do you still want to me to test these changes on my local setup ?

2022-01-06 13:05 UTC, ecino commented
It should be fine, I will test it on stage.

2022-01-06 13:05 UTC, merged