CP-405 Further refactor for invoicing system
CompassionCH/compassion-modules pull request #1722
Opened 2023-03-07 15:01 UTC by ecino

- [FIX] More granularity when updating a sponsorship. Prevents a change in one sponsorship to affect all other invoice lines in the same invoice.
- Move code to better isolate gift functionality inside sponsorship_compassion module instead of recurring_contract.

2023-03-08 13:52 UTC, simgonzalez requested changes

2023-03-08 13:52 UTC, simgonzalez commented on res_partner_compassion/models/res_partner.py
> +            data_invs = invoices._build_invoice_data(payment_term_id=self.property_payment_term_id.id)
```suggestion
            data_invs = invoices._build_invoices_data(payment_term_id=self.property_payment_term_id.id)
```

2023-03-08 13:52 UTC, simgonzalez commented on sponsorship_compassion/models/account_move.py
> +                open_invoices_exclude_sponsorship=True))._build_invoice_lines_from_contracts(modified_contracts)
```suggestion
        if self.invoice_category == "sponsorship":
            super = super()
        else:
            # Handle a gift or fund change
            super = super(AccountInvoice, self.with_context(
                open_invoices_exclude_sponsorship=True))
        return super._build_invoice_lines_from_contracts(modified_contracts) 
```

2023-03-08 13:52 UTC, simgonzalez commented on sponsorship_compassion/models/account_move_line.py
> +                    raise UserError(_("Unexpected error while updating contract invoices. Please contact admin."))
```suggestion
                if invoice_line.product_id.default_code == PRODUCT_GIFT_CHRISTMAS:
                    gift_type = 'christmas'
                elif invoice_line.product_id.default_code == GIFT_PRODUCTS_REF[0]:
                    gift_type = 'birthday'
                else:
                    raise UserError(_("Unexpected error while updating contract invoices. Please contact admin."))
                # Assign the price depending on the gift type
                data_dict["price_unit"] = eval('modified_contract.' + gift_type + '_invoice')
```

2023-03-08 13:52 UTC, simgonzalez commented on sponsorship_compassion/models/contracts.py
> +            data_invs = gifts._build_invoice_data(contracts=contracts)
```suggestion
            data_invs = gifts._build_invoices_data(contracts=contracts)
```

2023-03-09 07:49 UTC, ecino commented on sponsorship_compassion/models/account_move_line.py
> +                    raise UserError(_("Unexpected error while updating contract invoices. Please contact admin."))
```suggestion
                if invoice_line.product_id.default_code == PRODUCT_GIFT_CHRISTMAS:
                    gift_type = 'christmas_invoice'
                elif invoice_line.product_id.default_code == GIFT_PRODUCTS_REF[0]:
                    gift_type = 'birthday_invoice'
                else:
                    raise UserError(_("Unexpected error while updating contract invoices. Please contact admin."))
                # Assign the price depending on the gift type
                data_dict["price_unit"] = getattr(modified_contract, gift_type)
```

2023-03-09 09:16 UTC, simgonzalez approved these changes

2023-03-09 09:37 UTC, merged