T0015 14.0 crm_compassion migration
CompassionCH/compassion-modules pull request #1741
Opened 2023-04-13 09:37 UTC by ecino

2023-04-13 12:02 UTC, simgonzalez requested changes

2023-04-13 12:02 UTC, simgonzalez commented on crm_compassion/models/event_compassion.py
>      invoice_line_ids = fields.One2many(
Replacing invoice_line_ids by move_line_ids ?

2023-04-13 12:02 UTC, simgonzalez commented on crm_compassion/views/res_partner_view.xml
> +<!--    </record>-->
Why wouldn't we delete this code ?

2023-04-13 12:02 UTC, simgonzalez commented on crm_compassion/models/event_compassion.py
> +            event.balance = event.total_income - event.total_expense
It was a division and it became a substraction ?

2023-04-13 12:16 UTC, ecino commented on crm_compassion/models/event_compassion.py
> +            event.balance = event.total_income - event.total_expense
Yes, it didn't make any sense in v12! We discussed this with David. :laughing:

2023-04-13 12:20 UTC, ecino commented on crm_compassion/models/event_compassion.py
>      invoice_line_ids = fields.One2many(
It's just the field name, I don't think we need to rename it. BTW the same field name also exists in account.move table, which proves that it's not necessarily wrong to call the field like that even if it points to move.line object (because conceptually we are still talking about invoices, especially in this case).

2023-04-13 12:20 UTC, ecino commented on crm_compassion/views/res_partner_view.xml
> +<!--    </record>-->
I didn't see this one, I will remove it :+1:

2023-04-14 08:54 UTC, NoeBerdoz approved these changes

2023-04-17 07:47 UTC, merged