Add a base automation that automatically switch the communication for…
CompassionCH/compassion-modules pull request #1758
Opened 2023-05-10 10:11 UTC by simgonzalez

… partner when they go from W&P to normal Sponsorship

2023-05-12 07:08 UTC, NoeBerdoz approved these changes

2023-05-15 11:46 UTC, ecino requested changes
The changes should be moved into the module `partner_communication_compassion`

2023-05-15 12:17 UTC, ecino reviewed
After checking, I think this was already done here: https://github.com/CompassionCH/compassion-switzerland/blob/5dcfbe0d9557014c5265c74df49be149781aa9b3/partner_communication_switzerland/models/res_partner.py#L465

I don't like adding an automation based on the `on_write` trigger, because it will be checked each time a sponsorship is written which can greatly impact the performance. In my opinion we don't have anything to do regarding this task, except migrating the code for v14.

2023-05-16 08:45 UTC, ecino commented
Not an appropriate change.

2023-05-16 08:45 UTC, closed without merging