[T0648] FIX rename type beneficiary to participant
CompassionCH/compassion-modules pull request #1831
Opened 2023-11-03 12:38 UTC by NoeBerdoz

Related ticket: [T0648](https://erp.compassion.ch/web#id=1224&action=521&active_id=895&model=project.task&view_type=form&menu_id=924)

Beneficiary has been renamed to Participant

2023-11-16 13:02 UTC, ecino requested changes
I would prefer that you add the new value instead of replacing the existing one to make sure we have backward compatibility and don't lose the value of the old records.

2023-11-20 08:04 UTC, NoeBerdoz commented
> I would prefer that you add the new value instead of replacing the existing one to make sure we have backward compatibility and don't lose the value of the old records.

Done :+1:

2023-11-22 10:29 UTC, NoeBerdoz commented
@ecino 
I added a few changes, there was a related issue in household

2023-11-30 07:21 UTC, ecino approved these changes

2023-11-30 07:21 UTC, merged