T0644
CompassionCH/compassion-modules pull request #1845
Opened 2024-02-14 14:55 UTC by lucadela96

…sponsorships.

2024-02-15 11:33 UTC, ecino requested changes
Small improvements suggestions. You can also move your file into the `wizards` directory. This one contains all TransientModels used in popups. Don't forget also to run "pre-commit -a" in the repository in order to format the code correctly.

2024-02-15 11:33 UTC, ecino commented on sponsorship_compassion/models/res_partner_merge.py
> +            partner_ids.remove(dst_partner_id)
You can simplify this like that:
```suggestion
        partner_ids: List[int] = (self.partner_ids - self.dst_partner_id).ids
```

2024-02-15 11:33 UTC, ecino commented on sponsorship_compassion/models/res_partner_merge.py
> +SPONSORSHIP_TATE_ACTIVE = 'active'
```suggestion
SPONSORSHIP_STATE_ACTIVE = 'active'
```

2024-02-15 11:33 UTC, ecino commented on sponsorship_compassion/models/res_partner_merge.py
> +        active_sponsorship_contracts = self.env['recurring.contract'].search([
This will be a little more efficient
```suggestion
        active_sponsorship_contracts = self.env['recurring.contract'].search_count([
```

2024-02-15 12:17 UTC, lucadela96 commented on sponsorship_compassion/models/res_partner_merge.py
> +            ('state', '=', SPONSORSHIP_TATE_ACTIVE)
```suggestion
            ('state', '=', SPONSORSHIP_STATE_ACTIVE)
```

2024-03-07 08:34 UTC, ecino approved these changes

2024-03-07 08:36 UTC, merged