feat: Improved error messages for the forget_me method
CompassionCH/compassion-modules pull request #1987
Opened 2024-10-25 13:35 UTC by jordyBSK

Improved error messages for the forget_me method

2024-11-18 08:45 UTC, NoeBerdoz requested changes

2024-11-18 08:45 UTC, NoeBerdoz commented on sponsorship_compassion/models/res_partner.py
> +                    error_message = error_info.get("ErrorMessage", "Erreur inconnue")
The error message should be in English, and putted as a translatable text :
```_("Unknown error")```

2024-11-18 08:45 UTC, NoeBerdoz commented on sponsorship_compassion/models/res_partner.py
> +                    )
An error needs to be logged on the server, you can log it by using the logger provided by Odoo
`_logger.error(...)`

2024-11-18 08:47 UTC, NoeBerdoz commented on sponsorship_compassion/models/res_partner.py
> +                        f"an error occurred during data anonymisation.\n\n"
An error needs to be logged on the server, you can log it by using the logger provided by Odoo
`_logger.error(...)`

2024-12-09 07:28 UTC, ecino approved these changes

2024-12-09 07:28 UTC, merged