CO-1496 : limit for extra hours improved with SQL view for balances
CompassionCH/compassion-modules pull request #597
Opened 2018-03-12 07:20 UTC by samuel-fringeli

2018-03-12 07:36 UTC, ecino commented on hr_attendance_calendar/views/extra_hours_evolution_graph.xml
> +        <field name="context">{"graph_mode":"bar", "filter":[('employee_id', '=', user.id.employee_id)]}</field>
<field name="domain">[('employee_id', '=', user.id.employee_id)]</field>

2018-03-12 10:40 UTC, ecino commented
`hr_attendance_calendar/models/hr_attendance_day.py:240:26: E126 continuation line over-indented for hanging indent`

2018-03-12 10:53 UTC, ecino requested changes

2018-03-12 10:53 UTC, ecino commented on hr_attendance_calendar/models/hr_attendance_day.py
> +            if data.balance > max_extra_hours:
`if data.balance > max_extra_hours > 0:`
to avoid putting extra hours lost when the limit is not set (and is 0)

2018-03-12 10:53 UTC, ecino commented on hr_attendance_calendar/models/hr_attendance_day.py
> +                         'hr_attendance_calendar.max_extra_hours'))
`get_param('...', 0.0)` to return 0 by default if the parameter doesn't exist

2018-03-12 10:53 UTC, ecino commented on hr_attendance_calendar/models/hr_attendance_day.py
> +
The write method should return True

2018-03-12 10:53 UTC, ecino commented on hr_attendance_calendar/models/hr_attendance_day.py
> +    @api.depends('extra_hours')
You can remove the depends. Your method will already be called by your write method.

2018-03-12 10:53 UTC, ecino commented on hr_attendance_calendar/reports/extra_hours_evolution_day_report.py
> +    _name = "hr_attendance_day.extra_hours_evolution_day_report"
I would suggest `hr.attendance.balance.evolution.report` as shorter name. The convention is to not use `_` in model names.

2018-03-12 10:53 UTC, ecino commented on hr_attendance_calendar/reports/extra_hours_evolution_day_report.py
> +    employee_id = fields.Integer(string="employee_id")
You can change this to `fields.Many2one('hr.employee', 'Employee)`

2018-03-12 11:10 UTC, ecino commented
Do you think you can add a straight line in your graph at the max hours limit ? It would be good to quickly view when the employee has overcome the limit.

2018-03-12 14:45 UTC, eicher31 commented on hr_attendance_calendar/models/hr_attendance_day.py
> +    def compute_extra_hours_lost(self):
compute method must start with "_"

2018-03-12 14:47 UTC, eicher31 commented on hr_attendance_calendar/models/hr_attendance_day.py
> +    def compute_extra_hours_lost(self):
compute method must start with '_'

2018-03-13 10:00 UTC, ecino approved these changes

2018-03-13 13:57 UTC, merged