CO-1574 Add auto refresh for communication revisions
CompassionCH/compassion-modules pull request #621
Opened 2018-03-29 13:47 UTC by popod

2018-03-29 14:27 UTC, ecino requested changes

2018-03-29 14:27 UTC, ecino commented on partner_communication_revision/README.rst
> +Usagers
Usage not Usagers

2018-03-29 14:27 UTC, ecino commented on partner_communication_revision/models/communication_keyword.py
> +# from . import communication_revision as test
Remove this

2018-03-29 14:27 UTC, ecino commented on partner_communication_revision/models/communication_keyword.py
> +        # self.env['partner.communication.revision'].browse(self.revision_id.id).refresh_text()
Remove this

2018-04-03 10:23 UTC, popod commented
Has worked, but does not works anymore :(

2018-04-03 10:51 UTC, ecino commented
Maybe you can comment again the import of the xml loading the javascript in the manifest file, so that the js is not executed. But we can keep your code in the case we could use it in the future.

2018-04-03 14:56 UTC, ecino approved these changes

2018-04-03 14:56 UTC, merged