CO-1753: replace age mapping for child by computed field
CompassionCH/compassion-modules pull request #686
Opened 2018-06-19 08:09 UTC by samuel-fringeli

2018-06-20 11:31 UTC, ecino commented
Please check LINT errors

2018-06-22 08:06 UTC, samuel-fringeli commented
Pylint errors are corrected, but it stays flake8 errors that come from hr_attendance_extra_hours. However, there is no flake8 errors related to my commit.

2018-06-22 12:47 UTC, ecino requested changes

2018-06-22 12:47 UTC, ecino commented on child_compassion/models/global_child.py
> +            today = date.today()
Put this before the loop to improve optimization

2018-06-22 12:47 UTC, ecino commented on child_compassion/models/global_child.py
> +            born = datetime.strptime(child.birthdate, '%Y-%m-%d').date()
Better : `born = fields.Date.from_string(child.birthdate)`

2018-06-22 12:47 UTC, ecino commented on partner_communication/wizards/change_text_wizard.py
> +                ("You can only update text on one communication type at "
No! Put back that `_` and put it back from the imports. This is a translation function that translates the error strings to the user language.

2018-06-22 12:47 UTC, ecino commented on partner_communication/wizards/change_text_wizard.py
> +                ("Please update only one language at a time."))
Put back translation

2018-06-22 12:47 UTC, ecino commented on partner_communication/wizards/change_text_wizard.py
> +                ("You can only update text on one communication type at "
Put back translation

2018-06-22 12:48 UTC, ecino commented
These are your flake8 errors:
```
child_compassion/models/global_child.py:107:21: E126 continuation line over-indented for hanging indent
partner_communication/wizards/change_text_wizard.py:15:1: E302 expected 2 blank lines, found 1
partner_communication/wizards/change_text_wizard.py:18:80: E501 line too long (84 > 79 characters)
partner_communication/wizards/change_text_wizard.py:32:19: E127 continuation line over-indented for visual indent
partner_communication/wizards/change_text_wizard.py:52:19: E127 continuation line over-indented for visual indent
```

2018-06-25 12:07 UTC, samuel-fringeli commented
Voilà, j'ai tout corrigé

2018-06-25 13:11 UTC, ecino approved these changes

2018-06-25 13:11 UTC, merged