CO-1896 add missing reason + detailedReason to view
CompassionCH/compassion-modules pull request #726
Opened 2018-07-20 07:21 UTC by nbornand

2018-07-20 09:02 UTC, ecino commented
I will just check if I can find a documentation to look for possible other values

2018-07-20 11:30 UTC, ecino requested changes
1. You have conflicts.
2. Beware that there are two types of objects we have in Odoo, icp.lifecycle.reason and icp.suspension.extension.reason
3. In project_lifecycle_event.py, the Many2many fields seem wrongly defined, you should add the `relation` (https://www.odoo.com/documentation/10.0/reference/orm.html#relational-fields) parameter in the field definition, to avoid storing the relations in the same tables.
4. I have found a documentation and it seems that we have a lot more possible values.
```json
"ReasonForTransitionEnum" : 
		{
			"type": "string",
			"enum":
			[
				"Child Protection Issue",
				"Disaster Event",
				"Does not comply with policies",
				"Financial Mismanagement",
				"Other",
				"Successful Transition"
			]
		},
		"ReasonToExtendSuspensionEnum" : 
		{
			"type": "string",
			"enum":
			[
				"Church Leadership / Denomination Issues",
				"Compassion Processes Not Being Followed",
				"Financial Issues",
				"Fund Balance Beyond Standard Limits",
				"Government Restriction Issues",
				"ICP Leaders Do Not Show Commitment",
				"ICP Leadership Committee Issues",
				"ICP Management Practices Issues",
				"ICP Processes Not Followed By Staff",
				"ICP Staff Conflicts",
				"Integrity Issue",
				"Issues With Community",
				"Legal Issues",
				"Program Implemented Incorrectly",
				"Reports / Docs Not Meeting Standards",
				"Staffing Issues",
				"Work Environment Not Supporting Program"
			]
		},
		"SuspensionReasonEnum" : 
		{
			"type": "string",
			"enum":
			[
				"Accumulated Funds",
				"Child Protection Issue",
				"Church Leadership / Denomination Issues",
				"Community Issues",
				"Disaster Event",
				"Does Not Comply with Policies",
				"Financial Mismanagement",
				"Government Restriction",
				"ICP Leadership Lacks Commitment",
				"ICP Management Practices Do Not Meet PFM",
				"ICP Staffing Conflicts / Issues",
				"ICP is Unclear About FO Processes",
				"Integrity Issues",
				"Internal Issues in ICP Leadership",
				"Legal Issues",
				"Other",
				"Physical Work Environment Issues",
				"Program Implementation Issues",
				"Required Docs Do Not Meet Standards"
			]
		},
```

2018-07-23 09:43 UTC, nbornand commented
@ecino I've just fixed the four points and it seems to work fine now. The only problem is that the popup window is now huge

2018-07-23 11:31 UTC, ecino approved these changes

2018-07-23 11:31 UTC, merged