Co 1885 sync bin trays
CompassionCH/compassion-modules pull request #746
Opened 2018-07-30 14:18 UTC by nbornand

Waiting on https://github.com/OCA/report-print-send/pull/160/files or a local fork

2018-07-31 06:20 UTC, ecino requested changes
You should add security accesses to the model `printing.bin`

You can change in the file `oca_dependencies.txt` to make the repository `report_print_send` point to our CompassionCH fork.

2018-07-31 06:20 UTC, ecino commented on printer_output_tray/models/printing_printer.py
> +                              relation='',
relation is not a parameter of One2many field, you can remove it.

2018-07-31 06:20 UTC, ecino commented on printer_output_tray/models/printing_bin.py
> +    _name = 'printing.bin'
Should it be `printer.bin` or rename the class and description?

2018-07-31 07:42 UTC, nbornand commented on printer_output_tray/models/printing_bin.py
> +    _name = 'printing.bin'
Done for consistency with tray (class PrinterTray, 'printing.tray'). Though it doesn't quite make sense

2018-07-31 13:59 UTC, ecino commented on oca_dependencies.txt
> +report-print-send https://github.com/nbornand/report-print-send 10.0
CompassionCH instead of nbornand, because we merged your fix and we never know if you won't delete your repository after leavind :wink:

2018-07-31 14:00 UTC, ecino commented on printer_output_tray/models/printing_bin.py
> +    _name = 'printing.bin'
Ok

2018-07-31 14:01 UTC, ecino requested changes

2018-07-31 14:01 UTC, ecino commented on printer_output_tray/views/printing_printer.xml
> +<openerp>
Should be `odoo`

2018-07-31 14:01 UTC, ecino commented on printer_output_tray/views/printing_printer.xml
> +  <data noupdate="0">
noupdate="0" is by default yo you can simply remove the data tag.

2018-08-02 08:36 UTC, ecino approved these changes

2018-08-02 08:36 UTC, merged