Co 1947 event duration
CompassionCH/compassion-modules pull request #779
Opened 2018-08-17 12:56 UTC by nbornand

2018-08-28 09:10 UTC, ecino commented on crm_compassion/tests/test_crm_compassion.py
> +                'end_date': now + ' 8:43:00',
For what is that for? I think we should replace both start_date and end_date by `fields.Datetime.now()`

2018-08-28 12:20 UTC, ecino requested changes

2018-08-28 12:20 UTC, ecino commented on crm_compassion/models/event_compassion.py
> +            'duration': duration_in_hours,
I think now we still have the problem that if start_date == end_date, the duration will be 0? Maybe we should put here `duration_in_hours or 3` to put a minimum of 3 hours duration for instance?

2018-08-28 12:43 UTC, nbornand commented
To end up being 0, not only the dates must be the same but the hours as well. Will this really happen?

2018-08-28 16:10 UTC, ecino commented
This makes it possible : https://github.com/CompassionCH/compassion-modules/blob/10.0/crm_compassion/models/event_compassion.py#L413

Also I checked on production, I found 112 events with start_date=end_date.

2018-08-30 07:52 UTC, nbornand commented
now the duration is at least 3h

2018-08-30 14:38 UTC, ecino approved these changes

2018-08-30 14:38 UTC, merged